### ISSUE TITLE
unset PYTHONSTARTUP 

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/nersc#14]
NERSC's Cray OS sets PYTHONSTARTUP for all users, point to /etc/startup. This path does not exist in the shifter images, and is not useful for the `desc-python` kernel either.  I will unset PYTHONSTARTUP explicitly in the set up scripts.

**Comment by JulienPeloton** [comment]
@heather999 Just reading the scripts, the pyspark kernel is setting explicitly PYTHONSTARTUP and then sourcing the `${LSSTCONDA}/kernels/python.sh` which in turn source the `setup_current_python.sh` that unset the PYTHONSTARTUP... :D 

I will investigate tomorrow whether #15 has an impact for the pyspark kernel and report.

**Comment by heather999** [comment]
ok.. it is not such a big issue for the `setup_current_python.sh` to retain `PYTHONSTARTUP`, but it is a problem for the `desc-stack`.  So if it is a problem for pyspark, I can reinstate PYTYHONSTARTUP in `setup_current_python.sh`.  In fact, I think I'll just do that now. :)

**Comment by JulienPeloton** [comment]
Thanks @heather999!

**Comment by JulienPeloton** [comment]
pyspark kernel checked with the last release - all good! Thanks @heather999.
