### ISSUE TITLE
Update for Cori OS upgrade and removal of gcc 6.3.0

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/nersc#20]
gcc 6.3.0 is no longer available at NERSC, moving desc-python to use gcc 7.3.0

**Comment by cwwalter** [comment]
I think I missed this before.. why can't we have gcc 6.3.0 at NERSC anymore.  Surely, they just have to recompile it?

**Comment by heather999** [comment]
NERSC seems to follow the Cray software environment releases which explicitly include and exclude certain versions of software, such as gcc.  As it is gcc 6.3.0 was deprecated for the past year at NERSC.  We can inquire, but given that they do support gcc 7.3.0 which doesn't seem particularly cutting edge, is supported by DM, and is available via devtoolset-7, I think this isn't unreasonable.

**Comment by heather999** [comment]
Moved back to gcc 6.3.0 in the env for now.  Will revisit when we do a full reinstall of the conda environment
